### ISSUE TITLE
Installation of ibmdb driver on Darwin

### ISSUE THREAD

**Issue by jcurlier** [strongloop/loopback-connector-db2#1]
The installation of the dependency is failing on my Mac. I had the same issue with the ibmdb driver in the past and was able to resolve it by using the dependency `"ibm_db": "git+https://git@github.com/ibmdb/node-ibm_db.git#v4_support"` as documented here [https://github.com/ibmdb/node-ibm_db](https://github.com/ibmdb/node-ibm_db)

[npm-debug.log.zip](https://github.com/strongloop/loopback-connector-db2/files/101157/npm-debug.log.zip)
[install.log.zip](https://github.com/strongloop/loopback-connector-db2/files/101158/install.log.zip)

**Comment by tonyffrench** [comment]
Yes, we are working with the node-ibm_db to get this driver supported on version v4. You can run this on your Mac using NVM to manage your Node version. I'm currently developing and testing with v0.12.x. You'll also need to export DYLD_LIBRARY_PATH=<base path>/loopback-connector-db2/node_modules/ibm_db/installer/clidriver/lib/icc as per another issue listed over on https://github.com/ibmdb/node-ibm_db

**Comment by jcurlier** [comment]
Thanks, I had the same problem with DYLD_LIBRARY_PATH :) I am running on Mac with Node 4.2.4. Will wait for the update... I did a quick version Tuesday that I can use in the meantime https://github.com/jcurlier/loopback-connector-db2 - just using for the Retrieve...

**Comment by qpresley** [comment]
@jcurlier can you give this a try with the latest updates.  You'll likely still have to use the DYLD_LIBRARY_PATH trick but should no longer need the modified npm install command.

**Comment by jcurlier** [comment]
Still failed during the installaton of ibm_db...See log attached... I didn't have time to look into it.

**Comment by jcurlier** [comment]
I don't seem to be able to attach the log file.

**Comment by tonyffrench** [comment]
@jcurlier we hadn't published npm, you should be all set with version 1.0.2. Tested on v0.10.41, v0.12.9, v4.2.6, v5.5.0

**Comment by jcurlier** [comment]
Seems to work now - thanks - Note I still had to set DYLD_LIBRARY_PATH.
