### ISSUE TITLE
DB2 connector not working on the latest version of Loopback

### ISSUE THREAD

**Issue by ninoguba** [strongloop/loopback-connector-db2#121]
# Description/Steps to reproduce

When upgrading to the latest version 3.16.2 of Loopback, the DB2 Connector (version 2.1.0) doesnt work and outputs the following error message in the console for each datasource operation:

> Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0206N  "scopes" is not valid in the context where it is used.  SQLSTATE=42703

As a reference, our application is working fine when using LB 3.0.0 and DB2 Connector 2.0.0-alpha.

**Comment by ninoguba** [comment]
I think I have found the issue, related to missing the scopes column in the AccessToken table.

**Comment by dhmlau** [comment]
@ninoguba , it's good to hear you've found the cause of the problem.  Is it good to close? Thanks.

**Comment by ninoguba** [comment]
@dhmlau yes good to close. thanks!
