### ISSUE TITLE
Loopback - A communication error has been detected. DB2 High Availability 

### ISSUE THREAD

**Issue by zahidsalim** [strongloop/loopback-connector-db2#136]
I am getting Connection Timeout Error - A communication error has been detected. I am using DB2 High Availability instance on Cloud. Unable to connect to DB2 HA from my Loopback Application.

 Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "169.60.63.234".  Communication function detecting the error: "recv".  Protocol specific error code(s): "104", "*", "0".  SQLSTATE=08001.

I have to restart application very frequently.
Has anyone face the same issue and have fix if any.

**Comment by dhmlau** [comment]
@b-admike, you've recently looked into a few issues related to this connector. Could you please take a look at this too? Thanks.
