### ISSUE TITLE
Failure to report errors on creating new records

### ISSUE THREAD

**Issue by jdschreck** [strongloop/loopback-connector-db2#14]
When I use the PUT method on the api to put a new record in the database, it always returns the json of the record I tried to create and a Response Code of 200 even when I actually encounter errors and the record does not make it into the database.  I dug into db2.js and added an

if (err) console.log(err);

in the DB2.prototype.executeSQL function and then I finally saw the errors that were being encountered.  @qpresley please take a look.  I am not too familiar with javascript yet.  I am wondering if you are losing the value of err by using nextTick.

**Comment by qpresley** [comment]
@jdschreck I'll have a look today, I've been running into something related and haven't sorted it out yet.

**Comment by qpresley** [comment]
@jdschreck do you have a simple repro available for your scenario?

**Comment by jdschreck** [comment]
@qpresley I believe so.  I had a strongloop api talking to a mysql database originally.  One of the fields was defined as follows (I added the db2 stanza by hand when converting from mysql to db2): 
```
   "owner": {
      "type": "string",
      "required": false,
      "length": 65535,
      "precision": null,
      "scale": null,
      "mysql": {
        "columnName": "owner",
        "dataType": "text",
        "dataLength": 65535,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "Y"
      },
      "db2": {
        "columnName": "owner",
        "dataType": "VARCHAR",
        "dataLength": 50,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "Y"
      },
      "_selectable": true
    },
```

The error I am encountering is: 

> Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0604N The length, precision, or scale attribute for column, distinct type, structured type, array type, attribute of structured type, routine, cast target type, type mapping, or global variable "VARCHAR(65535)" is not valid. SQLSTATE=42611

So, it would seem to be trying to make use of the length defined to loopback, rather than the length that I gave it in the db2 stanza.  I am sure I am stretching things in a way they shouldn't be stretched.  It would have been nice if there was not a length in the loopback field definition and just
a length in the database specific stanza to allow some flexibility.  I suppose it might be a separate bug that something is not using the length specified in the database-specific definition and is instead using the general loopback field specification.  Not sure why they have it in both places.

**Comment by qpresley** [comment]
I need to re-work some code to get this functioning properly.  May take me a bit of time to get to it but I can see what needs to be done.

**Comment by qpresley** [comment]
@jdschreck latest code (and release 1.0.8 on npm) should contain the fix for this.  The one outstanding issue is with the nullable option in the stanza which is a more generic loopback issue which I have an issue open to track.

**Comment by jdschreck** [comment]
Thanks!
