### ISSUE TITLE
Schema gets overriden by DSN UID, generating inexistent tables.

### ISSUE THREAD

**Issue by lucasreta** [strongloop/loopback-connector-db2#145]
I had my CLI generated datasource config, it looked something like:

```
{
  "name": "db2",
  "connector": "db2",
  "dsn": "DATABASE=fdb;HOSTNAME=fake.host;PORT=50000;PROTOCOL=TCPIP;UID=UID_EXAMPLE;PWD=fakepass;",
  "host": "fake.host",
  "port": 50000,
  "user": "UID_EXAMPLE",
  "password": "fakepass",
  "database": "fdb",
  "schema": "schema_example"
}
```

The connection worked fine, as I could then generate models by using `lb4 discover`, so everything was going OK.

But then when I tried to get one of the endpoints for my SAMPLEMODEL, I got a 500 Error that said:

```
500 Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0204N  "UID_EXAMPLE.SAMPLEMODEL" is an undefined name.  SQLSTATE=42704
```

The CLI had warned about how the DSN would overwritte all other properties, so I first tried removing all other properties and leaving only the DSN, knowing the schema was also specified in the CLI generated Models. Doing so kept showing the same error, so I proceeded to delete the DSN from my config JSON, which ended up looking like this:

```
{
  "name": "db2",
  "connector": "db2",
  "host": "fake.host",
  "port": 50000,
  "user": "UID_EXAMPLE",
  "password": "fakepass",
  "database": "fdb",
  "schema": "schema_example"
}
```

After doing so, the queries started to work as expected.

I think is a minor bug, as it can be easily avoided by opting to leave out the DSN parameter, but still thought it would be good to report for reference and eventual fixing.

I could take a look at the code and try to fix the issue if needed, but first wanted to raise it here to see if the team was aware of it / know of possible implications behind fixing it.

Thanks for the good work!

**Comment by agnes512** [comment]
@emonddr could you take a look? thanks.
