### ISSUE TITLE
Make a transaction

### ISSUE THREAD

**Issue by simcor14** [strongloop/loopback-connector-db2#17]
Hi! I need to make a transaction in my server REST.

I have a Model "Wallet" and i want to start a transaction.
This is my code:

    `Wallet.beginTransaction({}, function(err, tx) {
          if (err) {
	
          } 
         //Other code
      });`

But i recived this error when i try to start transaction:

> AssertionError: beginTransaction must be function implemented by the connector

Can you help me?

Thanks

**Comment by Bisneff** [comment]
Same problem. Could be very useful if I understand how to make it works.

**Comment by qpresley** [comment]
Transaction support was added to the connect last week.  There are examples in the test/db2.transaction.test.js file in this repo that you can reference.
