### ISSUE TITLE
Adding schema setting

### ISSUE THREAD

**Issue by jcurlier** [strongloop/loopback-connector-db2#2]
When using a user DB2ADMIN to connect to my DB2 database that was created with another user such as ADMIN, the query fails.

Could we add a schema setting and then when building the connection string we could use the *CurrentSchema* setting:

`this.connectionString = "DRIVER={DB2};DATABASE=" + settings.database +        
    ";CurrentSchema=" + settings.schema + ";HOSTNAME=" + settings.host + 
    ";UID=" + settings.user + ";PWD=" + settings.password + 
    ";PORT=" + settings.port + ";PROTOCOL=TCPIP";`

**Comment by tonyffrench** [comment]
If you can confirm that this change is what your after, I'll publish a new version to npmjs. Didn't spend much time to understand if there is any inter-pay with SET CURRENT SCHEMA etc.
