### ISSUE TITLE
Offset and skip with SQL instead of JavaScript split

### ISSUE THREAD

**Issue by jcurlier** [strongloop/loopback-connector-db2#3]
It seems we are using a JavaScript split to keep only the records from a given row to a given row.

`if (offset || limit) {
      data = data.slice(offset, offset + limit);
    }
`

Should we do this as part of the SQL query to avoid transporting the data and parsing it? the Oracle driver is doing it this way. For example:

db2.prototype.buildColumnNames = function(model, filter) {
  var columnNames = this.invokeSuper('buildColumnNames', model, filter);
  if (filter.limit || filter.offset || filter.skip) {
    var orderBy = this.buildOrderBy(model, filter.order);
    columnNames += ',ROW_NUMBER() OVER' + ' (' + orderBy + ') rownum';
  }
  return columnNames;
};

db2.prototype.applyPagination = function(model, stmt, filter) {
  var offset = filter.offset || filter.skip || 0;

  var paginatedSQL = 'SELECT \* FROM ( ' + stmt.sql + ' ) WHERE rownum > ' + offset;

  if (filter.limit !== -1) {
    paginatedSQL += ' AND rownum <= ' + (offset + filter.limit);
  }

  stmt.sql = paginatedSQL + ' ';

  return stmt;
};

**Comment by tonyffrench** [comment]
Yes, we started looking at ROW_NUMBER(), offset is working well with FETCH FIRST x ROWS ONLY, trick will be to combine both of these. We also support the compatibility mode of using LIMIT and OFFSET.

**Comment by qpresley** [comment]
@jcurlier Do you mind if I close this?  DB2 V11 supports LIMIT/OFFSET natively but the older versions don't.  I'd rather move to the full implementation as the older DB2 versions go out of support.  I believe even with V10.5 you can set Oracle compatibility mode and use LIMIT/OFFSET

**Comment by jcurlier** [comment]
Sure - thanks
