### ISSUE TITLE
Support DB2 for iSeries version 7 and up

### ISSUE THREAD

**Issue by zenflow** [strongloop/loopback-connector-db2#30]
- Any plans to implement this? 
- Is this a feature that would be likely to be merged in with a PR? (Guidelines for contributing ask us to ensure our efforts are aligned with the project's roadmap.)
- Are there any barriers you are aware of?

**Comment by qpresley** [comment]
@zenflow It was not on the list to add but is definitely something that would be good to have and something I'm sure we'll get requests for.  I'm hoping that the underlying SQL is not much different but need to run some tests to see where the gaps are.

**Comment by qpresley** [comment]
Please see https://github.com/strongloop/loopback-connector-db2iseries
