### ISSUE TITLE
REST endpoint `PUT` will update the property for all instance instead of the specific one

### ISSUE THREAD

**Issue by ssh24** [strongloop/loopback-connector-db2#32]
Following the steps:

1. slc loopback
2. slc loopback:datasource to create a db2 instance
3. slc loopback:model to create a model attach to db2 instance
4. run node . and open explorer
5. create several instances
6. Try PUT/models with data:
{
 "property_name": "new_value",
 "id": "instance_id"
}
7. Try GET/models

then all instances' property would be updated to "new_value"

**Comment by qpresley** [comment]
This has been fixed.  Please re-open if you still hit an issue.
