### ISSUE TITLE
DB2 connector does not work properly for APIC when given the DSN string

### ISSUE THREAD

**Issue by ssh24** [strongloop/loopback-connector-db2#34]
1. create a default hello-world loopback app (apic loopback appname)
2. run apic edit
3. create a datasource with db2 connector
4. put in the required credentials just as a DSN string and leave the config fields such as hostname, port and etc. empty
5. connect the datasource

The DB2 connection fails given the DSN string.

This is most likely a problem in the DB2 connector where the connect function checks for a set of variables and if any of them are not set it fails with "Invalid Connection String". 

The connection ignores the DSN string when given and there should also be a test added to the DB2 connector to ensure that when only a DSN is specified that the connection is still successful.

**Comment by jannyHou** [comment]
@ssh24 Thank you.
I should check `dsn` as well in https://github.com/strongloop/loopback-connector-db2/blob/master/lib/db2.js#L161-L165
Will fix it ASAP

**Comment by jannyHou** [comment]
@ssh24 could you verify if the issue fixed with the latest code in loopback-connector-db2?

**Comment by ssh24** [comment]
`Verified.`

<img width="1258" alt="api designer - ibm api connect - mozilla firefox ibm edition firefox today at 11 45 38 am" src="https://cloud.githubusercontent.com/assets/15173354/15328953/eddeda44-1c24-11e6-9786-21070e4ccc13.png">

`Closed.`
