### ISSUE TITLE
DB2 connector- support for migrate and discovery

### ISSUE THREAD

**Issue by cgole** [strongloop/loopback-connector-db2#37]

**Comment by qpresley** [comment]
@cgole Can the team verify this now exists.  It should work unless I'm missing detail on how you are using it.

**Comment by gabrielmancini** [comment]
+1

**Comment by qpresley** [comment]
@cgole Please see above comment on getting this verified.

**Comment by qpresley** [comment]
@cgole  Closing as I'm sure this is done
