### ISSUE TITLE
Unable to install loopback connector for IBM DB2

### ISSUE THREAD

**Issue by Midhuntcs** [strongloop/loopback-connector-db2#39]
Hi,

While I am trying to install loopback connector for IBM DB2, I am getting the below error;

`? Install loopback-connector-db2@^1.0.0 Yes
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail o
n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible
. Use 'npm ls graceful-fs' to find it in the tree.

> ibm_db@0.0.19 install D:\official\office works\loopback\DB2try\employee_detail
s\node_modules\ibm_db
> node installer/driverInstall.js

Windows 32 bit not supported. Please use an x64 architecture.
employee_details@1.0.0 D:\official\office works\loopback\DB2try\employee_details

`-- loopback-connector-db2@1.0.17
  +-- async@1.5.2
  `-- ibm_db@0.0.19
    +-- bindings@1.0.0
    +-- fstream@1.0.10
    +-- nan@2.2.1
    +-- tar.gz@0.1.1
    | +-- commander@1.1.1
    | +-- fstream@0.1.31
    | | `-- graceful-fs@3.0.8
    | `-- tar@0.1.20
    |   +-- block-stream@0.0.9
    |   `-- fstream@0.1.31
    |     `-- graceful-fs@3.0.8
    `-- unzip@0.1.11
      +-- binary@0.3.0
      | +-- buffers@0.1.1
      | `-- chainsaw@0.1.0
      |   `-- traverse@0.3.9
      +-- fstream@0.1.31
      | `-- graceful-fs@3.0.8
      +-- match-stream@0.0.2
      | `-- readable-stream@1.0.34
      |   `-- isarray@0.0.1
      +-- pullstream@0.4.1
      | +-- over@0.0.5
      | +-- readable-stream@1.0.34
      | | `-- isarray@0.0.1
      | `-- slice-stream@1.0.0
      |   `-- readable-stream@1.0.34
      |     `-- isarray@0.0.1
      +-- readable-stream@1.0.34
      | `-- isarray@0.0.1
      `-- setimmediate@1.0.4

Done running loopback generator

Updating swagger and product definitions
Error: The LoopBack application is not loaded.

WARNING: LoopBack connector "db2" is not installed as any of the following modul
es:

 ./connectors/db2
loopback-connector-db2

To fix, run:

    npm install loopback-connector-db2

Cannot load the LoopBack application: Cannot create data source "IBMDB2":
WARNING: LoopBack connector "db2" is not installed as any of the following modul
es:

 ./connectors/db2
loopback-connector-db2

To fix, run:

    npm install loopback-connector-db2

Please fix the problem and run `apic loopback:refresh`

`
My npm version is 3.9.2 and node version is 4.4.2.
Kindly help me to resolve the issue.

**Comment by qpresley** [comment]
@Midhuntcs The underlying node-ibm_db module found at https://github.com/ibmdb/node-ibm_db has a requirement for 64 bit Windows and will not successfully install on 32 bit Windows.  If it does not install neither will the loopback-connector-db2 module.

**Comment by qpresley** [comment]
Closing this issue as 32 bit Windows install will not be supported.
