### ISSUE TITLE
By overriding the builtin authentication models, DB2.js destroyAll method is not working

### ISSUE THREAD

**Issue by naveen-venkat** [strongloop/loopback-connector-db2#45]
Hello @qpresley,

Thank you very much for the support, WRT the issue https://github.com/strongloop/loopback/issues/2615.

In db2.js as shown below, its trying to build a DELETE query with SELECT which is similar to create method which is failing, the sql query it prepares as below,

SELECT "id" FROM OLD TABLE (DELETE FROM "T0040ACCESS_TOKEN" WHERE "ACCESS_TOKEN_ID"=(?))

The "id" column above in the SELECT statement should have been "ACCESS_TOKEN_ID". Can you please help us on this? Also i believe, we would be facing similar issue in update as well?

The error returned is below, 
[IBM][CLI Driver][DB2/LINUXX8664] SQL0206N "id" is not valid in the context where it is used. SQLSTATE=42703

/**
 * Delete all matching model instances
 *
 * @param {string} model The model name
 * @param {Object} where The where object
 * @param {Object} options The options object
 * @param {Function} cb The callback function
 */
DB2.prototype.destroyAll = function(model, where, options, cb) {
  debug('DB2.prototype.destroyAll: model=%s, where=%j, options=%j',
        model, where, options);
  var self = this;
  var stmt = self.buildDelete(model, where, options);
  var idName = self.idName(model);
  var sql = 'SELECT \"' + idName + '\" FROM OLD TABLE (' + stmt.sql + ')';
  self.execute(sql, stmt.params, options, function(err, info) {
    if (cb) {
      cb(err, {count: info.length});
    }
  });
};

Thanks,
Naveen

**Comment by qpresley** [comment]
Can you send me the updated version of the JSON file for this model.  I'll continue to look into this one today.

**Comment by naveen-venkat** [comment]
following is the access token json model, please let me know if we need to connect on a call.

{
  "name": "CptAccessToken",
  "base": "AccessToken",
  "idInjection": false,
  "db2": {
    "table": "ABC"
  },
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "id": {
      "id": true,
      "type": "string",
      "db2": {
        "columnName": "ACCESS_TOKEN_ID",
        "dataType": "VARCHAR",
        "dataLength": 255
      }
    },
    "userId": {
      "db2": {
        "columnName": "USER_ID",
        "dataType": "BIGINT"
      }
    },
    "ttl": {
      "type": "number",
      "db2": {
        "columnName": "TTL"
      }
    },
    "created": {
      "type": "date",
      "db2": {
        "columnName": "CREATED_TIMESTAMP",
        "dataType": "TIMESTAMP"
      }
    }
  },
  "validations": [],
  "relations": {
    "user": {
      "type": "belongsTo",
      "model": "PensionsUser",
      "foreignKey": "userId"
    }
  },
  "acls": [
    {
      "property": "find",
      "accessType": "*",
      "permission": "ALLOW",
      "principalType": "ROLE",
      "principalId": "$everyone"
    },
    {
      "property": "deleteById",
      "accessType": "*",
      "permission": "ALLOW",
      "principalType": "ROLE",
      "principalId": "$everyone"
    }
  ],
  "methods": {}
}

**Comment by qpresley** [comment]
@naveen-venkat Found the issue, I need to discuss more with some of the loopback team to get a fix.  Will get back to you shortly.

**Comment by qpresley** [comment]
@naveen-venkat 1.0.20 was just uploaded to npmjs.org.  Give it a try it should fix the issues you were seeing.

**Comment by whitehorse5353** [comment]
@qpresley thanks it works fine

**Comment by naveen-venkat** [comment]
great!!
