### ISSUE TITLE
DB2 Query hangs forever without any results

### ISSUE THREAD

**Issue by libraxyz** [strongloop/loopback-connector-db2#50]
Hi all,
My table in Db2 is of following type
db2 describe table BSP.COVER                                                       

```
                            Data type                     Column
```

Column name                     schema    Data type name      Length     Scale Nulls

---

ID                              SYSIBM    BIGINT                       8     0 No  
PROJECT                         SYSIBM    VARCHAR                     50     0 No  
EVENTNAME                       SYSIBM    VARCHAR                    200     0 No  
ENTITY                          SYSIBM    VARCHAR                    100     0 No  
HIERARCHY                       SYSIBM    VARCHAR                    250     0 No  
EVENTCLASS                      SYSIBM    VARCHAR                    200     0 No  
EVENTGROUPKEY                   SYSIBM    VARCHAR                     50     0 No  
EVENTGROUPFILTER                SYSIBM    VARCHAR                    250     0 Yes  
**COUNT                           SYSIBM    BIGINT                       8     0 Yes**  
COVERAGESTATUS                  SYSIBM    VARCHAR                     20     0 No  
MAXCOUNT                        SYSIBM    BIGINT                       8     0 Yes  
MODIFIED                        SYSIBM    TIMESTAMP                   10     6 No
MAXCOUNTDATE                    SYSIBM    DATE                         4     0 Yes
LASTHITDATE                     SYSIBM    DATE                         4     0 Yes
FIRSTHITDATE                    SYSIBM    DATE                         4     0 Yes
AGEOUTDATE                      SYSIBM    DATE                         4     0 Yes
DIRECTEDTESTNAME                SYSIBM    VARCHAR                    500     0 Yes
OWNER                           SYSIBM    VARCHAR                     50     0 Yes
TRIAGESTATUS                    SYSIBM    VARCHAR                     50     0 Yes
PRIORITY                        SYSIBM    INTEGER                      4     0 Yes
COMMENT                         SYSIBM    VARCHAR                   1000     0 Yes
LASTHITTESTDIR                  SYSIBM    VARCHAR                    500     0 Yes
LASTHITTESTNAME                 SYSIBM    VARCHAR                    256     0 Yes
TESTCOUNT                       SYSIBM    BIGINT                       8     0 Yes
TAG                             SYSIBM    VARCHAR                    100     0 No
EVENTBIRTHDATE                  SYSIBM    DATE                         4     0 No
TRACKERDATE                     SYSIBM    DATE                         4     0 No
MRCLEAN                         SYSIBM    VARCHAR                     25     0 Yes
DEFECTNUMBER                    SYSIBM    VARCHAR                     50     0 Yes
DEFECTSTATUS                    SYSIBM    VARCHAR                     20     0 Yes
DEFECTCREATEDATE                SYSIBM    DATE                         4     0 Yes
DEFECTSEVERITY                  SYSIBM    INTEGER                      4     0 Yes
DELETEDATE                      SYSIBM    DATE                         4     0 Yes
DELETEUSER                      SYSIBM    VARCHAR                     50     0 Yes
DELETED                         SYSIBM    SMALLINT                     2     0 Yes
USERDATA0                       SYSIBM    VARCHAR                    100     0 Yes
USERDATA1                       SYSIBM    VARCHAR                    100     0 Yes
USERDATA2                       SYSIBM    VARCHAR                    100     0 Yes
ONE_OF_EACH_COUNT               SYSIBM    INTEGER                      4     0 Yes
MODIFIEDBY                      SYSIBM    VARCHAR                     50     0 Yes
HARVEST                         SYSIBM    INTEGER                      4     0 No
TREND                           SYSIBM    INTEGER                      4     0 No
CRONNOTES                       SYSIBM    VARCHAR                    200     0 Yes
AUTOPROCESS                     SYSIBM    VARCHAR                    500     0 Yes
ECLASS                          SYSIBM    INTEGER                      4     0 No
COLORMAP                        SYSIBM    VARCHAR                     32     0 Yes
RANK                            SYSIBM    SMALLINT                     2     0 No
VIRTUAL_TAG                     SYSIBM    VARCHAR                    100     0 Yes
DESCRIPTION                     SYSIBM    VARCHAR                   1000     0 Yes

I have set DEBUG="_connector_,_datasource_"
 When I am running a query for this table, 

 SELECT "ID","PROJECT","EVENTNAME","ENTITY","HIERARCHY","EVENTCLASS","EVENTGROUPKEY","EVENTGROUPFILTER","COUNT","COVERAGESTATUS","MAXCOUNT","MODIFIED","MAXCOUNTDATE","LASTHITDATE","FIRSTHITDATE","AGEOUTDATE","DIRECTEDTESTNAME","OWNER","TRIAGESTATUS","PRIORITY","COMMENT","LASTHITTESTDIR","LASTHITTESTNAME","TESTCOUNT","TAG","EVENTBIRTHDATE","TRACKERDATE","MRCLEAN","DEFECTNUMBER","DEFECTSTATUS","DEFECTCREATEDATE","DEFECTSEVERITY","DELETEDATE","DELETED","USERDATA0","USERDATA1","USERDATA2","ONE_OF_EACH_COUNT","MODIFIEDBY","HARVEST","TREND","CRONNOTES","AUTOPROCESS","ECLASS","COLORMAP","RANK","VIRTUAL_TAG","DESCRIPTION" FROM "COVER" WHERE **"COUNT"=(?) ORDER BY "ID" FETCH FIRST 10 ROWS ONLY [ 0 ] {}**

I don't get any value back
While on the actual db2 machine, I see records being returned.
Other queries works fine.

I am using strong-loop to create REST APIs.

**Comment by qpresley** [comment]
@libraxyz Sorry it has taken so long to get a response on this.  Can you provide the debug output you received.  You should really only need to set DEBUG=loopback:connector:*
