### ISSUE TITLE
How to do a SELECT DISTINCT with DB2 connector using Angular SDK

### ISSUE THREAD

**Issue by FelipeMiranda** [strongloop/loopback-connector-db2#76]
### Bug or feature request

- [* ] Bug
- [X ] Feature request

### Description of feature (or steps to reproduce if bug)
How do I do a find() distinct using the angular SDK query?

**Comment by qpresley** [comment]
This looks like something you would need to do through customer sql using the execute or executeSQL functions of the connector.  Have a look at https://loopback.io/doc/en/lb3/Executing-native-SQL.html
