### ISSUE TITLE
DB2 container instead of plain install

### ISSUE THREAD

**Issue by andrefernandes** [strongloop/loopback-connector-db2#96]
Testing is *way* more easily done with the db2express Docker image. Maybe instructions should point to it instead?

**Comment by dhmlau** [comment]
That's a good idea.  I guess you're referring to the `README.md`?  Would you like to submit a PR?

**Comment by andrevtg** [comment]
Sure, I wrote that before doing it myself. Happy to share. brb....

**Comment by dhmlau** [comment]
connect to: https://github.com/strongloop/loopback-connector-db2/pull/100

**Comment by andrefernandes** [comment]
just noticed that I opened the issue and submitted the PR under another github id. Sorry for the mess.
