### ISSUE TITLE
Relations data is missing in discoverSchemas response

### ISSUE THREAD

**Issue by Swapnil-Girme** [strongloop/loopback-connector-db2#97]
Problem statement:
discoverSchemas response doesn’t contain relations data. I have provided relations as true in options and table MANAGER has a foreign key relationship with EMP table, but discoverSchemas response for MANAGER table gives relations as an empty object.

**Comment by sonia1588** [comment]
PR raised #101

**Comment by ssh24** [comment]
PR landed: https://github.com/strongloop/loopback-connector-db2/pull/105
