### ISSUE TITLE
buildQueryPrimaryKeys () does not return Primary key details for DB2 database

### ISSUE THREAD

**Issue by pooja-kothari** [strongloop/loopback-connector-db2#99]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
buildQueryPrimaryKeys () method of discovery.js (line no 204) does not return primary key details although table has primary key in it.
Further to our analysis method used below query to fetch primary key details:
`SELECT TRIM(tabschema) AS "owner", TRIM(tabname) AS "tableName", TRIM(colname) AS "columnName", colseq AS "keySeq", constname AS "pkName" FROM syscat.keycoluse WHERE  constname = 'PRIMARY' AND tabname = 'SOME_TABLE_NAME' ORDER BY tabschema, constname, tabname, colseq`

In the query the condition "constname = 'PRIMARY'" causing the issue as in DB2 connector the default constname for primary key is not "PRIMARY" but some other unique value.

### Expected result
Method should return primary key details as response.

### Actual result (if bug)
Method is returning empty response

**Comment by ssh24** [comment]
PR landed: https://github.com/strongloop/loopback-connector-db2/pull/103
